platform: linux

image_resource:
  type: docker-image
  source:
    repository: 'python'
    tag: '2'

inputs:
- name: apt-scripts

outputs:
- name: rent-data

run:
  path: ./apt-scripts/jobs/pull-rents/pull-rents.sh

params:
  PULL_RENTS_USERNAME: <%= ENV['PULL_RENTS_USERNAME'] %>
  PULL_RENTS_PASSWORD: <%= ENV['PULL_RENTS_PASSWORD'] %>
  PULL_RENTS_SOURCE_URL: <%= ENV['PULL_RENTS_SOURCE_URL'] %>
  PULL_RENTS_DEST_URL: <%= ENV['PULL_RENTS_DEST_URL'] %>
  SHARED_DRIVE_PASSWORD: <%= ENV['SHARED_DRIVE_PASSWORD'] %>
  SHARED_DRIVE_USERNAME: <%= ENV['SHARED_DRIVE_USERNAME'] %>
  SHARED_DRIVE_URL: <%= ENV['SHARED_DRIVE_URL'] %>
  APT_SCRIPTS_URL: <%= ENV['APT_SCRIPTS_URL'] %>

resource_types:
- name: samba-resource
  type: docker-image
  source:
      repository: airtonix/concourse-resource-samba
      tag: latest

resources:
- name: apt-scripts
  type: git
  source:
    uri: <%= ENV['APT_SCRIPTS_URL'] %>
- name: shared-drive
  type: samba-resource
  source:
    server: <%= ENV['SHARED_DRIVE_URL'] %>
    share: storage
    user : <%= ENV['SHARED_DRIVE_USERNAME'] %>
    password: <%= ENV['SHARED_DRIVE_PASSWORD'] %>

jobs:
- name: pull-rent-data
  plan:
  - get: apt-scripts
  - get: shared-drive
    params: { "path" : "/share/projects/Apartments/stream/" }
  - task: crawl-rents
    file: apt-scripts/jobs/crawl-rents/crawl-rents.yml
  - put: shared-drive
    params: { "path" : "/share/projects/Apartments/stream/" }
- name: merge-data
  plan:
  - get: shared-drive
    params: { "path" : "/share/projects/Apartments/stream/" }
  - put: shared-drive
    params: { "path" : "/share/projects/Apartments/views/vizualization" }