resources:
- name: apt-scripts
  type: git
  source:
    uri: https://github.com/uiuc-bdeep/Apartments.git
    branch: master

jobs:
- name: pull-rents
  plan:
  - get: flight-school
  - task: tests
    file: flight-school/build.yml
